# Do not run workflow for now
name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    container:
      image: dart:latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: dart pub get

      - name: Build Runner
        run: dart pub run build_runner build --delete-conflicting-outputs

      - name: Run tests
        run: dart pub run test

      - name: Publish Dart package
        uses: k-paxian/dart-package-publisher@master
        with:
          refreshToken: ${{ secrets.REFRESH_TOKEN }}
          accessToken: ${{ secrets.ACCESS_TOKEN }}
